backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "termsofservice"
    label: "Terms of Service"
    files:
    - label: "Terms of Service"
      name: "termsofservice"
      file: "content/termsofservice.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "privacypolicy"
    label: "Privacy Policy"
    files:
    - label: "Privacy Policy"
      name: "privacypolicy"
      file: "content/privacypolicy.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "paymentmethods"
    label: "Payment Methods"
    files:
    - label: "Payment Methods"
      name: "paymentmethods"
      file: "content/paymentmethods.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "pricingandrates"
    label: "Pricing and Rates"
    files:
    - label: "Pricing and Rates"
      name: "pricingandrates"
      file: "content/pricingandrates.md"
      fields:
        - { label: "Old School Runescape Rate (07)", name: "osrsrate", widget: "number"}
        - { label: "Runescape 3 Rate (RS3)", name: "rs3rate", widget: "number"}
        - { label: "Giftcard Discount Percentage", name: "giftcarddiscount", widget: "number"}