backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "logocomponent"
    label: "Logo Component"
    files: 
    - label: "Logo Component"
      name: "logocomponent"
      file: "content/logocomponent.md"
      fields: 
        - { label: 'Header Image', name: "headerimage", widget: 'image'}
        - { label: 'Alt Text', name: "alttext", widget: 'string'}
  - name: "generalinfocomponent"
    label: "General Information Component"
    files:
    - label: "General Information Component"
      name: "generalinfocomponent"
      file: "content/generalinfocomponent.md"
      fields: 
       - { label: 'Title', name: 'title', widget: 'string'}
       - { label: 'First Body', name: 'firstbody', widget: 'string'}
       - label: "Pictures"
         name: 'pictures'
         widget: list
         fields: 
          - { label: "Picture", name: "picture", widget: "image"}
          - { label: "Alt Text", name: "alttext", widget: "string"}
       - { label: 'Second Title', name: 'secondtitle', widget: 'string'}
       - { label: 'Second Body', name: 'secondbody', widget: 'string'}
       - { label: 'Third Title', name: 'thirdtitle', widget: 'string'}
       - { label: 'Third Body', name: 'thirdbody', widget: 'string'}
  - name: "howtobegincomponent"
    label: "How to Begin Component"
    files:
    - label: "How to Begin Component"
      name: "howtobegincomponent"
      file: "content/howtobegincomponent.md"
      fields:
      - { label: "title", name: 'title', widget: 'string'}
      - label: "Sections"
        name: "sections"
        widget: list
        fields:
          - { label: "Picture", name: "picture", widget: 'image'}
          - { label: "Alt Text", name: "alttext", widget: 'string'}
          - { label: "Sub Picture", name: "subpicture", widget: 'image'}
          - { label: "Sub Picture Alt Text", name: "subalttext", widget: 'string'}
          - { label: "Text", name: "text", widget: 'string'}
  - name: "RWT Information Component"
    label: "rwtinfocomponent"
    files:
    - label: "RWT Information Component"
      name: "rwtinfocomponent"
      files: "content/rwtinfocomponent.md"
      fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Body Paragraph", name: "bodyparagraph", widget: 'markdown'}


  - name: "termsofservice"
    label: "Terms of Service"
    files:
    - label: "Terms of Service"
      name: "termsofservice"
      file: "content/termsofservice.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "privacypolicy"
    label: "Privacy Policy"
    files:
    - label: "Privacy Policy"
      name: "privacypolicy"
      file: "content/privacypolicy.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "paymentmethods"
    label: "Payment Methods"
    files:
    - label: "Payment Methods"
      name: "paymentmethods"
      file: "content/paymentmethods.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "pricingandrates"
    label: "Pricing and Rates"
    files:
    - label: "Pricing and Rates"
      name: "pricingandrates"
      file: "content/pricingandrates.md"
      fields:
        - { label: "Old School Runescape Rate (07)", name: "osrsrate", widget: "string"}
        - { label: "Runescape 3 Rate (RS3)", name: "rs3rate", widget: "string"}
        - { label: "OSRS to RS3 SWAP RATE (OSRS -> RS3)", name: "osrstors3swap", widget: "string"}
        - { label: "RS3 to OSRS SWAP RATE (RS3 -> OSRS)", name: "rs3toosrsswap", widget: "string"}
  - name: "videogamegiftcards"
    label: "Video Game Giftcards"
    files:
    - label: "Video Game Giftcards"
      name: "videogamegiftcards"
      file: "content/videogamegiftcards.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Giftcard Discount Percentage", name: "giftcarddiscount", widget: "string"}
        - label: 'Video Game Giftcards'
          name: "videogamegiftcards"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Denominations", name: "denominations", widget: "string" }
            - { label: "Giftcard Image", name: "image", widget: "image" }
            - { label: "Description", name: "description", widget: "string" }
  - name: "runescapeaccounts"
    label: "Runescape Accounts"
    files:
    - label: "Runescape Accounts"
      name: "accounts"
      file: "content/runescapeaccounts.md"
      fields:
        - label: 'Runescape Accounts'
          name: "accounts"
          widget: list
          fields:
            - { label: "Identifier", name: "identifier", widget: "string"}
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Gamemode", name: "gamemode", widget: "select", options: ["OSRS", "RS3"]}
            - { label: "Account Level", name: "accountlevel", widget: "select", options: ["Started", "Med", "Maxed"]}
            - { label: "Price", name: "price", widget: "string"}
            - { label: "Categories", name: "category", widget: "select", options: ["Main", "Pure", "Zerk", "Obby Mauler", "Skiller", "Misc", "Staker" ] }
            - { label: "Thumbnail", name: "thumbnail", widget: "image" }
            - { label: "Description", name: "description", widget: "markdown" }
            - { label: "Publish Time", name: "publishdate", widget: "datetime", default: "", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL", picker_utc: false }
  - name: "reviews"
    label: "Feedback And Reviews"
    files:
    - label: "Feedback And Reviews"
      name: "reviews"
      file: "content/reviews.md"
      fields:
        - label: 'Feedback And Reviews'
          name: "reviews"
          widget: list
          fields:
            - { label: "Identifier", name: "id", widget: "string"}
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Message", name: "message", widget: "markdown" }
            - { label: "Category", name: "category", widget: "select", options: ["TrustPilot", "Sythe", "OSBot", "EpicNPC"]}
            - { label: "Link", name: "link", widget: "string" }
            - { label: "Publish Date", name: "publishdate", widget: "datetime", default: '', date_format: "DD.MM.YYYY", format: "LLL", picker_utc: false}