backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "termsofservice"
    label: "Terms of Service"
    files:
    - label: "Terms of Service"
      name: "termsofservice"
      file: "content/termsofservice.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "privacypolicy"
    label: "Privacy Policy"
    files:
    - label: "Privacy Policy"
      name: "privacypolicy"
      file: "content/privacypolicy.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}